# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

target 'qrtc_flutter_ios_plugin' do
    use_frameworks!
    use_modular_headers!
  
    pod 'Starscream', '~> 3.0.2'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'HydraAsync'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'SnapKit'
    pod 'Toast-Swift'
    pod 'Material'
    pod 'SDWebImage'
    pod 'Alamofire', '~> 5.2'
  
  end
  